# 2 : Analyse des éléments de symétrie

In [5]:
import numpy as np
import matplotlib.pyplot as plt

from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.analysis.diffraction.xrd import XRDCalculator

from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter

from scipy.optimize import curve_fit
from scipy.constants import hbar, k as k_B

API_KEY = "vKJsFu0jdhLy7CJj5Mwar6S68kxgMc3n"
MP_ID = "mp-1008556"  

with MPRester(API_KEY) as mpr:
    structure = mpr.get_structure_by_material_id(MP_ID)


#from jupyter_jsmol.pymatgen import quick_view

In [6]:
# Préparation des données
analyzer = SpacegroupAnalyzer(structure)
symm_ops = analyzer.get_symmetry_operations()
sites = structure.sites

# On affiche la liste pour choisir nos indices
# for i, op in enumerate(symm_ops):
#     print(f"Index {i}: {op.as_xyz_string()}")

In [12]:
# Symétries choisies (on évite 0 et 1 qui sont l'identité)
S1 = sym[4]  # Index 4 : Rotation (-x, -y, z)
S2 = sym[8]  # Index 8 : Miroir (x, -y, z)
S3 = sym[2]  # Index 2 : Roto-inversion (-y, x, -z)

# Atomes choisis
Al = structure.sites[0].frac_coords
Ga = structure.sites[1].frac_coords
N = structure.sites[2].frac_coords

# Application des symétries
Al_sym = S1.operate(Al)
Ga_sym = S2.operate(Ga)
N_sym = S3.operate(N)

In [11]:
print("Liste des opérations disponibles :")
for i, operation in enumerate(sym):
    print(f"Index {i} : {operation.as_xyz_str()}")

Liste des opérations disponibles :
Index 0 : x, y, z
Index 1 : x, y, z
Index 2 : -y, x, -z
Index 3 : -y, x, -z
Index 4 : -x, -y, z
Index 5 : -x, -y, z
Index 6 : y, -x, -z
Index 7 : y, -x, -z
Index 8 : x, -y, z
Index 9 : x, -y, z
Index 10 : -y, -x, -z
Index 11 : -y, -x, -z
Index 12 : -x, y, z
Index 13 : -x, y, z
Index 14 : y, x, -z
Index 15 : y, x, -z


### Première opération : Rotation d'ordre 2 sur l'Aluminium (Al)

Nous allons étudier l'opération de rotation d'ordre 2 ($C_2$) autour de l'axe z sur l'atome d'Aluminium. Mathématiquement, cette opération inverse les coordonnées x et y tout en conservant z. Elle est définie comme ceci : 

$$\begin{pmatrix} x' \\ y' \\ z' \end{pmatrix} = \begin{pmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix}$$

On remarque que le vecteur de translation $\tau$ est nul. 
Le déterminant de la matrice vaut 1. Il s'agit d'une opération de première espèce (rotation propre) qui conserve la chiralité.

In [13]:
print("Opération de symétrie 1 : \n")
print(f"L'atome de départ est l'Al et a comme coordonnées : {Al}\n")
# La commande correcte pour votre version est as_xyz_str()
print(f"On lui applique l'opération ({S1.as_xyz_str()}) :\n")
print(S1.rotation_matrix, "*", Al, '+', S1.translation_vector)
print(f"L'atome d'arrivée a comme coordonnées : {Al_sym}\n")

# --- Visualisation JSmol ---
# (Laissez les # si JSmol bloque toujours)
# from jupyter_jsmol.pymatgen import quick_view
# v1 = quick_view(structure)
# display(v1)
# v1.script("draw symop 2 {atomno=1}")

Opération de symétrie 1 : 

L'atome de départ est l'Al et a comme coordonnées : [0.5 0.5 0.5]

On lui applique l'opération (-x, -y, z) :

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]] * [0.5 0.5 0.5] + [0. 0. 0.]
L'atome d'arrivée a comme coordonnées : [-0.5 -0.5  0.5]

